In [65]:
import pandas as pd

df = pd.read_csv("orders.csv")

In [10]:
product_and_country = df.loc[:, ["Product", "Country"]]

In [11]:
print(product_and_country)

                  Product       Country
0                  Laptop           USA
1              Headphones        Canada
2            Office Chair           UAE
3               Desk Lamp     Singapore
4                Keyboard        Mexico
5                Notebook           UAE
6           Standing Desk            UK
7                 Monitor   South Korea
8                     Pen         Italy
9                   Mouse         Japan
10                 Webcam        France
11           File Cabinet         India
12                Stapler     Australia
13              USB Drive         Spain
14              Bookshelf         China
15          Printer Paper         Egypt
16         Wireless Mouse        Poland
17         Desk Organizer           USA
18             Calculator         Japan
19             Whiteboard  Saudi Arabia
20           Highlighters        Canada
21      Bluetooth Speaker        Brazil
22           Office Plant       Germany
23           Sticky Notes      Pakistan
24           Tablet Stand        Sweden
25         Paper Shredder        France
26         Desk Chair Mat     Argentina
27           Binder Clips        Russia
28      Wireless Keyboard   South Korea
29          Desk Calendar         Italy
30                USB Hub       Morocco
31       Document Scanner       Germany
32  Desk Drawer Organizer      Colombia
33            Index Cards           USA
34          Monitor Stand         Japan
35     Desk Lamp with USB            UK
36       Wireless Earbuds      Portugal
37               Desk Pad          Iran
38            Power Strip   South Korea
39             Desk Clock       Ukraine

In [17]:
print(df.loc[:, ["Product", "Country"]].tail())

               Product      Country
35  Desk Lamp with USB           UK
36    Wireless Earbuds     Portugal
37            Desk Pad         Iran
38         Power Strip  South Korea
39          Desk Clock      Ukraine

In [18]:
df.info

<bound method DataFrame.info of     OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas MÃ¼ller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine  >

In [19]:
df.describe

<bound method NDFrame.describe of     OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas MÃ¼ller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine  >

In [20]:
df["Country"]

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: object

In [ ]:
df[["Country", "Product"]] #using the dataframe df, we are simply printing out 2 columns with every row, 
                           #if we wanted specific rows, we use loc

         Country                Product
0            USA                 Laptop
1         Canada             Headphones
2            UAE           Office Chair
3      Singapore              Desk Lamp
4         Mexico               Keyboard
5            UAE               Notebook
6             UK          Standing Desk
7    South Korea                Monitor
8          Italy                    Pen
9          Japan                  Mouse
10        France                 Webcam
11         India           File Cabinet
12     Australia                Stapler
13         Spain              USB Drive
14         China              Bookshelf
15         Egypt          Printer Paper
16        Poland         Wireless Mouse
17           USA         Desk Organizer
18         Japan             Calculator
19  Saudi Arabia             Whiteboard
20        Canada           Highlighters
21        Brazil      Bluetooth Speaker
22       Germany           Office Plant
23      Pakistan           Sticky Notes
24        Sweden           Tablet Stand
25        France         Paper Shredder
26     Argentina         Desk Chair Mat
27        Russia           Binder Clips
28   South Korea      Wireless Keyboard
29         Italy          Desk Calendar
30       Morocco                USB Hub
31       Germany       Document Scanner
32      Colombia  Desk Drawer Organizer
33           USA            Index Cards
34         Japan          Monitor Stand
35            UK     Desk Lamp with USB
36      Portugal       Wireless Earbuds
37          Iran               Desk Pad
38   South Korea            Power Strip
39       Ukraine             Desk Clock

In [ ]:
df.loc[6:7, ["Product", "Country"]] #loc, slicing is inclusive

         Product      Country
6  Standing Desk           UK
7        Monitor  South Korea

In [ ]:
df.iloc[6:8, 6:8] #iloc, note: when slicing with iloc, both positions are exclusive

    OrderDate Shipped
6  2024-06-08     Yes
7  2024-06-09      No

In [44]:
more1 = df[df["Quantity"] > 1] #filtering using booleans

In [40]:
df[df["Category"] == "Electronics"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [ ]:
df[(df["Category"] == "Electronics") & (df["Country"] == "Brazil")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil

In [47]:
more1.sort_values("Price", ascending=False) #simple sorting

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [ ]:
df["price_per_item"] = df["Price"] / df["Quantity"]
df["price_per_item"] #adding and modifying columns, making new column derived from the division of 2 other columns

0     1200.000000
1       75.000000
2      300.000000
3       15.000000
4       40.000000
5        1.000000
6      450.000000
7      110.000000
8        0.150000
9       35.000000
10      85.000000
11      90.000000
12       4.000000
13       5.000000
14     280.000000
15       0.400000
16      22.500000
17      65.000000
18      15.000000
19     120.000000
20       0.437500
21      95.000000
22      17.500000
23       0.266667
24      28.000000
25      75.000000
26      22.000000
27       0.208333
28     110.000000
29      18.000000
30      32.000000
31     140.000000
32      42.000000
33       0.008000
34      55.000000
35      68.000000
36     125.000000
37      28.000000
38       9.000000
39      35.000000
Name: price_per_item, dtype: float64

In [71]:
df.fillna({"Product": "Headphone"}, inplace=True) #replacing data
df

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Headphones,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [77]:
group = df.groupby("Country")["Price"].sum()
group.sort_values(ascending=False)

Country
USA             1265.8
UK               518.0
South Korea      348.0
UAE              305.0
China            280.0
India            180.0
Germany          175.0
France           160.0
Canada           153.5
Portugal         125.0
Saudi Arabia     120.0
Japan            105.0
Brazil            95.0
Mexico            80.0
Singapore         45.0
Poland            45.0
Colombia          42.0
Ukraine           35.0
Morocco           32.0
Sweden            28.0
Iran              28.0
Spain             25.0
Argentina         22.0
Italy             19.5
Australia         12.0
Egypt              8.0
Pakistan           4.0
Russia             2.5
Name: Price, dtype: float64

In [78]:
df.groupby("Country")["Price"].sum().sort_values(ascending=False)

Country
USA             1265.8
UK               518.0
South Korea      348.0
UAE              305.0
China            280.0
India            180.0
Germany          175.0
France           160.0
Canada           153.5
Portugal         125.0
Saudi Arabia     120.0
Japan            105.0
Brazil            95.0
Mexico            80.0
Singapore         45.0
Poland            45.0
Colombia          42.0
Ukraine           35.0
Morocco           32.0
Sweden            28.0
Iran              28.0
Spain             25.0
Argentina         22.0
Italy             19.5
Australia         12.0
Egypt              8.0
Pakistan           4.0
Russia             2.5
Name: Price, dtype: float64

In [79]:
df.shape

(40, 9)

In [80]:
df.describe

<bound method NDFrame.describe of     OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith             Headphones  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas MÃ¼ller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine  >